### ISSUE TITLE
Queens Blade

### ISSUE THREAD

**Issue by LilyC-Dev** [LilyC-Dev/warband_mod_source#15]
I got permission to use the assets from the Queens Blade (https://www.nexusmods.com/mbwarband/mods/6195) awhile ago and have been thinking about how to implement it. If anyone has any ideas on what to do with the assets let me know. 

Currently I am working on adding in the Combat Overhaul OSP. (https://forums.taleworlds.com/index.php/topic,353860.0.html)

**Comment by LilyC-Dev** [comment]
@IntelligencePending Is it actually possible to allow players to toggle clothing for certain troops??

**Comment by MitchPTI** [comment]
Let me know what items should be added to/removed from each troop if it's toggled on and I'll set up the scripting for that.
