### ISSUE TITLE
1.3 Pre-release

### ISSUE THREAD

**Issue by IntelligencePending** [LilyC-Dev/warband_mod_source#22]
The current github is in a really good place right now in terms of content and bugfixes. It's got lots of new things and is much more stable than the current 1.20, so I think it's time we should consider wrapping up the new content and releasing 1.30.

However, lots of big things changed these past two days though, so perhaps a pre-release version should be made so that more people can playtest it before we call the current version "stable".

**Comment by Elminzter** [comment]
yea its a good idea for pre-release

**Comment by LilyC-Dev** [comment]
I completely agree, I just need to add in the credits / documentation and I can zip it, one way this could be done is labeling it as 1.30-Staging, and then if there are any major bugs those could be fixed and put into a 1.30 full release.
