### ISSUE TITLE
Money/equipment lost after sneaking into town for spy mission

### ISSUE THREAD

**Issue by MitchPTI** [LilyC-Dev/warband_mod_source#27]
https://www.reddit.com/r/mountandblade/comments/9cboos/dickplomacy_reloaded

"Not sure if its a dickplomacy reloaded problem. But i just did a spy mission where i sneak into a city as a pilgrim and talk to a spy. Ive spoken to the spy and left the city but all my stuff is gone? My money, food, gear. All gone. Meaning i cant feed my troops and they are pissed. Anyone else getting this?"

**Comment by IntelligencePending** [comment]
Bug is fixed in 1.3, but the current release is using 1.2 - Can't post on Reddit because my account is too new but sent you a PM with the info.
